# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build Package

on:
  push:
    branches: ["prod"]
  # pull_request:
  #   branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: SwiftyLab/setup-swift@latest
        # with:
        #   swift-version: "5.1.0"
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
